#!/bin/bash
# 구글 플레이스토어 배포 완료 안내

echo "🎉 구글 플레이스토어 배포 준비 완료!"
echo "=================================="
echo ""
echo "📱 생성된 App Bundle 파일:"
echo "   파일: build/app/outputs/bundle/release/app-release.aab"
echo "   크기: $(ls -lh build/app/outputs/bundle/release/app-release.aab | awk '{print $5}')"
echo ""
echo "🎯 다음 단계:"
echo "1. 구글 플레이 콘솔(play.google.com/console)에 로그인"
echo "2. 새 앱 만들기 선택"
echo "3. 앱 이름: '두뇌트레이닝: 수학' 입력"
echo "4. 앱 카테고리: 교육 > 수학"
echo "5. '업로드할 App Bundle을 여기에 드롭하세요' 영역에"
echo "   app-release.aab 파일을 드래그 앤 드롭"
echo ""
echo "📋 앱 정보:"
echo "   • 앱 이름: 두뇌트레이닝: 수학"
echo "   • 패키지 ID: com.tenspoon.math_training"
echo "   • 버전: 1.0.0 (빌드 1)"
echo "   • 아이콘: 512x512px 준비됨"
echo "   • 설명: 2000자 한글 설명 준비됨"
echo ""
echo "🚀 업로드 후 추가 설정:"
echo "   • 앱 아이콘 업로드 (app_icons/app_icon_512x512.png)"
echo "   • 스크린샷 추가 (게임 플레이 화면)"
echo "   • 앱 설명 입력 (준비된 2000자 설명 사용)"
echo "   • 연령 등급 설정 (전체 이용가 또는 3+)"
echo "   • 개인정보 처리방침 URL (필요시)"
echo ""
echo "✨ 축하합니다! 앱이 플레이스토어 배포 준비 완료되었습니다!"
